### ISSUE TITLE
Set the correct default upload URL

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-easy-image#1]
To the one we use in the manual test, which is: `https://files.cke-cs.com/upload/`

@wwalc and @czerwonkabartosz – is it the right one?

**Comment by czerwonkabartosz** [comment]
Yes, this is correct URL to production environment. I wonder if the production environment should be used for testing, but for this moment `https://files.cke-cs.com/upload/` is a correct URL for this.

**Comment by Reinmar** [comment]
If we'll decide to use a different URL for tests, then we'll change it in the manual test (and perhaps some demos) only. While it's good to know that this is a correct default value.

**Comment by wwalc** [comment]
Let's have the production URL until the situation forces us to figure out something different. For example when working on breaking API changes while having to maintain the old API on production intact.
