### ISSUE TITLE
CKEditor5 - Paste Image and upload to Shared server

### ISSUE THREAD

**Issue by SKGGitHub** [ckeditor/ckeditor5-easy-image#16]
Hello Team,

I had setup CKEditor5 for my React application as source and building it with my application as we need to make some customization as per client needs.

Requirement - User should be able to paste or drag and drop image to editor and once dropped or pasted a call should go to upload image to shared server (our owned application shared server for such resources) and then we will save id of that image to db and then return URL of that image to UI for editor to bind that URL with image. Any working example and guidance would be of great help.

Thanks.

**Comment by SKGGitHub** [comment]
As per further analysis I found that to use "Easy Image" we need to subscribe to CKEditor5 cloud services. If yes then what is the alternate to it if we want to use our shared server to keep images and provide our own customized URL to that image. Please point in right direction.

**Comment by pjasiun** [comment]
Yes, Easy Image is a working out of the box solution which uses Cloud Services as a backend. If you want to use your custom backend you can check [this doc](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload.html) and [this SO answear](https://stackoverflow.com/questions/46765197/how-to-enable-image-upload-support-in-ckeditor-5). CKEditor 5 will provide image feature and handle dropped or pasted images but you need to provide server integration as well as the whole backend code if you do not want to use Easy Image.

**Comment by SKGGitHub** [comment]
So, what are the alternates to EasyImage. Link you provided talk about EasyImage setup only. So what else we should use for Image upload for CKEDitor5.

**Comment by Reinmar** [comment]
You can find the answer in https://stackoverflow.com/questions/46765197/how-to-enable-image-upload-support-in-ckeditor-5.

**Comment by wwalc** [comment]
The answer for the above questions will be covered by https://github.com/ckeditor/ckeditor5/issues/618. I'm fully aware that it's much easier to create something having a nice tutorial, but for now you have to follow the hints in the [answer on StackOverflow](https://stackoverflow.com/questions/46765197/how-to-enable-image-upload-support-in-ckeditor-5) and by looking at how the CKFinder upload adapter works.

**Comment by SKGGitHub** [comment]
I am happy to catch up on hints. 

We already using other editor and application is already in place to upload image which is doing nicely. so back end service to upload image and return back URL is all ready. I just need to know how I can write my custom adapter to link that service with CKeditor5. That application is built using Tinymce but we find CKEditor5 much better so want to use CKEditor5 for our new app but will utilize backend of existing app.
