### ISSUE TITLE
Please remove node_modules from your published packages

### ISSUE THREAD

**Issue by esserj** [ckeditor/ckeditor5-easy-image#21]
It seems like easy-image and related packages all have their node_modules folders uploaded
this means we get a gazulion duplicate files, once in the root, and once in every of the related packages.

**Comment by Reinmar** [comment]
Hi! I don't think it's even possible to publish `node_modules`. I guess – not, because that's a folder used by npm.

Also, we've got the list of files configured: https://github.com/ckeditor/ckeditor5-easy-image/blob/master/package.json#L40

If you get `node_modules` in all CKEditor 5 packages, it means that either you use a very old npm version or use mismatched versions of CKEditor 5 packages – i.e. for example a ckeditor5-basic-styles which requres a different version of ckeditor5-engine than let's say ckeditor5-image.

**Comment by pomek** [comment]
https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

> By default, the following paths and files are ignored, so there's no need to add them to .npmignore explicitly:
>
> [...]
>
> Additionally, everything in node_modules is ignored, except for bundled dependencies. npm automatically handles this for you, so don't bother adding node_modules to .npmignore.

**Comment by pomek** [comment]
Based on the above, npm does not publish `node_modules` directory.

**Comment by pomek** [comment]
But even if the mechanism desrcibed above would fail, we have defined [`files`](https://docs.npmjs.com/files/package.json#files) key in `package.json` that says to NPM what shout be published:

https://github.com/ckeditor/ckeditor5-easy-image/blob/30c79a47523d5de104383d089ede18ef41c8c568/package.json#L40-L44

**Comment by esserj** [comment]
Strange, as i only get node_modules in your packages and not in any other.... hmm not sure whats then happening here

**Comment by ma2ciek** [comment]
Could you list versions of ckeditor5 packages you install? They probably mismatch a little bit.

**Comment by esserj** [comment]
@ma2ciek that is indeed whats happening, I was not aware of the fact the npm was inlining dependencies when they mismatch from the main, i still had ckeditor code ^10.0 while we have 11 now it seems

**Comment by esserj** [comment]
tnx @ma2ciek, I just think that this npm behaviour is very strange, I dont want it to install incompatible version but rather warn me, building web dependencies is already a mess, this just add insult to injury imo, im gona see if there is a way to tell npm not to install any packages that are not compatible with me root dependencies

**Comment by ma2ciek** [comment]
Thanks for the honest opinion @esserj. We're planning to remove some dependencies of dependencies or make them peer dependencies. We're aware of this problem and we'll for sure do something in this area in the near future.

**Comment by ma2ciek** [comment]
> im gona see if there is a way to tell npm not to install any packages that are not compatible with me root dependencies

This should work okay if you have latest CKEditor 5 dependencies listed in the `package.json`
